spring:
  application:
    name: task-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskdb}
    username: ${SPRING_DATASOURCE_USERNAME:taskapi}
    password: ${SPRING_DATASOURCE_PASSWORD:taskapi}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
